### ISSUE TITLE
Error: $ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by emiltb** [mikkelkrogsholm/ftDK#1]
When fetching the 'stemme' endpoint I get the following error at 31% completion. 

    library(ftDK)
    ft_stemme <- get_ft('stemme')
    #> Fetching 315724 rows of data
    #>   |++++++++++++++++                                  | 31% ~14m 46s
    #> Error in ft_data$value : $ operator is invalid for atomic vectors

This also occurs for another large dataset 'sagaktoer'

    ft_stemme <- get_ft('sagaktoer')
    #> Fetching 309753 rows of data
    #> |++++++++++++++++                                  | 32% ~13m 50s      
    #> Error: $ operator is invalid for atomic vectors

I have not tried to load all the different endpoints, this was just from sampling a few.

**Comment by mikkelkrogsholm** [comment]
Yes, something happens in the pull from the API. I got the same error at exactly 31% as well. 
Do you have time to debug the code to see whats going on?
